export const STORE_DATA = [
  {
    id: '1',
    name: 'Kid Girl Flutter-sleeve Tee',
    price: 1200,
    image: require('./products/p1-1.webp'),
    allImages: [
      require('./products/p1-1.webp'),
      require('./products/p1-2.webp'),
      require('./products/p1-3.webp'),
    ],
    description: 'Flutter sleeves add a fun touch to this soft cotton tee.',
    category: 'shirts',
    quantity: 1,
    collection: 'Summer Collection 2023',
    rating: 3,
    sale: true,
  },
  {
    id: '2',
    name: 'Frock with red shirt',
    price: 1800,
    image: require('./products/p2-1.webp'),
    allImages: [
      require('./products/p2-1.webp'),
      require('./products/p2-2.webp'),
      require('./products/p2-3.webp'),
    ],
    description: 'A red t-shirt, perfect for days with non-red weather.',
    category: 'shirts',
    quantity: 1,
    collection: 'Summer Collection 2023',
    rating: 4,
    sale: true,
  },
  {
    id: '3',
    name: 'Pink Shirt and trouser',
    price: 2000,
    image: require('./products/p3-1.webp'),
    allImages: [
      require('./products/p3-1.webp'),
      require('./products/p3-2.webp'),
      require('./products/p3-3.webp'),
    ],
    description: 'A red t-shirt, perfect for days with non-red weather.',
    category: 'shirts',
    quantity: 1,
    collection: 'Summer Collection 2023',
    rating: 5,
    sale: true,
  },
  {
    id: '4',
    name: 'Dinosaur Tee',
    price: 1099,
    image: require('./products/p4-1.webp'),
    allImages: [
      require('./products/p4-1.webp'),
      require('./products/p4-2.webp'),
      require('./products/p4-3.webp'),
    ],
    description: 'A red t-shirt, perfect for days with non-red weather.',
    category: 'shirts',
    quantity: 1,
    collection: 'Summer Collection 2023',
    rating: 3,
    featured: true,
  },
  {
    id: '5',
    name: 'Brown frock with white shirt',
    price: 2999,
    image: require('./products/p5-1.webp'),
    allImages: [
      require('./products/p5-1.webp'),
      require('./products/p5-2.webp'),
      require('./products/p5-3.webp'),
    ],
    description: 'A red t-shirt, perfect for days with non-red weather.',
    category: 'shirts',
    quantity: 1,
    collection: 'Summer Collection 2023',
    rating: 3,
  },
  {
    id: '6',
    name: 'Green tank top with black knickers',
    price: 1199,
    image: require('./products/p6-1.webp'),
    allImages: [
      require('./products/p6-1.webp'),
      require('./products/p6-2.webp'),
      require('./products/p6-3.webp'),
    ],
    description: 'A red t-shirt, perfect for days with non-red weather.',
    category: 'shirts',
    quantity: 1,
    collection: 'New Arrivals',
    rating: 5,
    sale: true,
  },
  {
    id: '7',
    name: 'Indepence day T-shirt',
    price: 2199,
    image: require('./products/p7-1.webp'),
    allImages: [
      require('./products/p7-1.webp'),
      require('./products/p7-2.webp'),
      require('./products/p7-3.webp'),
    ],
    description: 'A red t-shirt, perfect for days with non-red weather.',
    category: 'shirts',
    quantity: 1,
    collection: 'New Arrivals',
    rating: 2,
    featured: true,
  },
  {
    id: '8',
    name: 'T-shirt with shorts',
    price: 1999,
    image: require('./products/p8-1.webp'),
    allImages: [
      require('./products/p8-1.webp'),
      require('./products/p8-2.webp'),
      require('./products/p8-3.webp'),
    ],
    description: 'A red t-shirt, perfect for days with non-red weather.',
    category: 'shirts',
    quantity: 1,
    collection: 'New Arrivals',
    rating: 4,
    featured: true,
  },
  {
    id: '9',
    name: 'Red Shirt',
    price: 2149,
    image: require('./products/p8-1.webp'),
    allImages: [
      require('./products/p8-1.webp'),
      require('./products/p8-2.webp'),
      require('./products/p8-3.webp'),
    ],
    description: 'A red t-shirt, perfect for days with non-red weather.',
    category: 'shirts',
    quantity: 1,
    collection: 'New Arrivals',
    rating: 5,
    featured: true,
  },
  {
    id: '10',
    name: 'Red Shirt',
    price: 2649,
    image: require('./products/p8-1.webp'),
    allImages: [
      require('./products/p8-1.webp'),
      require('./products/p8-2.webp'),
      require('./products/p8-3.webp'),
    ],
    description: 'A red t-shirt, perfect for days with non-red weather.',
    category: 'shirts',
    quantity: 1,
    collection: 'New Arrivals',
    rating: 5,
    featured: false,
  },
  {
    id: '11',
    name: 'Red Shirt',
    price: 2749,
    image: require('./products/p8-1.webp'),
    allImages: [
      require('./products/p8-1.webp'),
      require('./products/p8-2.webp'),
      require('./products/p8-3.webp'),
    ],
    description: 'A red t-shirt, perfect for days with non-red weather.',
    category: 'shirts',
    quantity: 1,
    collection: 'New Arrivals',
    rating: 3,
    featured: false,
  },
  {
    id: '12',
    name: 'Red Shirt',
    price: 2999,
    image: require('./products/p8-1.webp'),
    allImages: [
      require('./products/p8-1.webp'),
      require('./products/p8-2.webp'),
      require('./products/p8-3.webp'),
    ],
    description: 'A red t-shirt, perfect for days with non-red weather.',
    category: 'shirts',
    quantity: 1,
    collection: 'New Arrivals',
    rating: 4,
    featured: false,
  },
  {
    id: '13',
    name: 'Red Shirt',
    price: 2199,
    image: require('./products/p8-1.webp'),
    allImages: [
      require('./products/p8-1.webp'),
      require('./products/p8-2.webp'),
      require('./products/p8-3.webp'),
    ],
    description: 'A red t-shirt, perfect for days with non-red weather.',
    category: 'shirts',
    quantity: 1,
    collection: 'New Arrivals',
    rating: 5,
    featured: false,
  },
  {
    id: '14',
    name: 'Red Shirt',
    price: 1299,
    image: require('./products/p8-1.webp'),
    allImages: [
      require('./products/p8-1.webp'),
      require('./products/p8-2.webp'),
      require('./products/p8-3.webp'),
    ],
    description: 'A red t-shirt, perfect for days with non-red weather.',
    category: 'shirts',
    quantity: 1,
    collection: 'New Arrivals',
    rating: 5,
    featured: false,
  },
  {
    id: '15',
    name: 'Red Shirt',
    price: 1599,
    image: require('./products/p8-1.webp'),
    allImages: [
      require('./products/p8-1.webp'),
      require('./products/p8-2.webp'),
      require('./products/p8-3.webp'),
    ],
    description: 'A red t-shirt, perfect for days with non-red weather.',
    category: 'shirts',
    quantity: 1,
    collection: 'New Arrivals',
    rating: 4,
    featured: false,
  },
  {
    id: '16',
    name: 'Red Shirt',
    price: 2999,
    image: require('./products/p8-1.webp'),
    allImages: [
      require('./products/p8-1.webp'),
      require('./products/p8-2.webp'),
      require('./products/p8-3.webp'),
    ],
    description: 'A red t-shirt, perfect for days with non-red weather.',
    category: 'shirts',
    quantity: 1,
    collection: 'New Arrivals',
    rating: 3,
    featured: false,
  },
  {
    id: '17',
    name: 'Red Shirt',
    price: 2999,
    image: require('./products/p8-1.webp'),
    allImages: [
      require('./products/p8-1.webp'),
      require('./products/p8-2.webp'),
      require('./products/p8-3.webp'),
    ],
    description: 'A red t-shirt, perfect for days with non-red weather.',
    category: 'shirts',
    quantity: 1,
    collection: 'New Arrivals',
    rating: 3,
    featured: false,
  },
];
